backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields: 
        - { label: "Title", name: "title", widget: "string"}
        - label: "Sections"
          name: "sections"
          widget: "list"
          fields:
            - { label: "Section Title", name: "title", widget: "string"}
            - { label: "Section Body", name: "body", widget: "markdown"}
        