backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields: 

        - { label: "Title", name: "title", widget: "markdown", buttons: [], required: false }
        - { label: "Subtitle", name: "subtitle", widget: "markdown", buttons: [], required: false }

        - label: "Sections"
          name: "sections"
          widget: "list"
          fields:
            - { label: "Section Id", name: "id", widget: "string"}
            - { label: "Type", name: "type", widget: "select", options: ["paragraph", "cards", "links"], default: ["paragraph"]}
            - { label: "Alignment", name: "alignment", widget: "select", options: ["container-start", "container-center", "container-end"], default: ["container-start"]}
            - { label: "Section Title", name: "title", widget: "markdown", buttons: [], required: false}
            - { label: "Section Subtitle", name: "subtitle", widget: "markdown", buttons: [], required: false }

            - { label: "Section Body", name: "body", widget: "markdown", required: false }

            - label: "Section Cards"
              name: "cards"
              widget: "list"
              required: false
              fields:
                - { label: "Card Title", name: "title", widget: "string", required: false}
                - { label: "Card Subtitle", name: "subtitle", widget: "string", required: false}
                - { label: "Card Date", name: "date", widget: "string", required: false}
                - { label: "Card Content", name: "body", widget: "markdown", required: false}
                - label: "Card Images"
                  name: "images"
                  widget: "list"
                  required: false
                  field: {label: Image, name: image, widget: image, required: false}

            - label: "Section Links"
              name: "links"
              widget: "list"
              required: false
              fields:
                - { label: "Link Title", name: "title", widget: "string", required: false}
                - { label: "Link Icon", name: "icon", widget: "string", required: false}
                - { label: "Link Address", name: "address", widget: "string", required: false}

        